spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    open-in-view: false
logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
